# Generated by Django 5.1.7 on 2025-04-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
